apiVersion: v2
name: lataupe-bunker-tech
description: A Helm chart for Lataupe Bunker Tech secure application
type: application
version: 2.0.0
appVersion: "2.0.0"
keywords:
  - bunker
  - security
  - survival
  - monitoring
home: https://bunker.tech
sources:
  - https://github.com/kvnbbg/lataupe-bunker-tech
maintainers:
  - name: Lataupe Bunker Tech Team
    email: admin@bunker.tech
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
