import os
import sys
# DON'T EDIT THIS FILE!
# This file is auto-generated by the script in the root directory.
# If you want to make changes, edit the script instead.
sys.path.insert(0,
    os.path.dirname(os.path.dirname(__file__)))

from flask import Flask, send_from_directory
from flask_cors import CORS
from src.models.user import db
from src.models.bunker import BunkerUser, EnvironmentalsData, Alert, EmergencyMessage
from src.routes.user import user_bp
from src.routes.auth import auth_bp
from src.routes.dashboard import dashboard_bp
from src.routes.emergency import emergency_bp

app = Flask(__name__, static_folder=os.path.join(os.path.dirname(__file__),'static'))

# Configure CORS pour permettre les requêtes cross-origin
CORS(app, supports_credentials=True)

# Configuration de la base de données
app.config['SECRET_KEY'] = 'bunker-tech-secret-key-change-in-production'
app.config['SESSION_COOKIE_SECURE'] = False # True en production avec HTTPS
app.config['SESSION_COOKIE_HTTPONLY'] = True # True pour empêcher l'accès JavaScript to the cookie
app.config['SESSION_COOKIE_SAMESITE'] = 'Lax' # Lax pour les requêtes cross-site

# Configuration de la base de données
app.config['SQLALCHEMY_DATABASE_URI'] ='sqlite:///bunker.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
